In [19]:
import numpy as np
from sklearn.metrics.pairwise import cosine_distances
from scipy.spatial.distance import euclidean, cityblock 

In [20]:
A = np.array([11,22,70,85,91])
B = np.array([69,44,75,36,500])

In [21]:
eucl_dist = euclidean(A,B)
print("Euclidean distance:",eucl_dist)

Euclidean distance: 416.5993278919206


In [22]:
manhattan_dist =cityblock(A,B)
print("Manhattan distance:",manhattan_dist)

Manhattan distance: 543


In [23]:
cosine_dist = cosine_distances(A.reshape(1, -1), B.reshape(1, -1))[0][0]
print("Cosine distance:",cosine_dist)

Cosine distance: 0.2537720276849622


In [24]:
cosine_dist = cosine_distances([A],[B])[0][0]
print("Cosine distance:",cosine_dist)

Cosine distance: 0.2537720276849622


In [25]:
cosine_sim = 1 - cosine_dist
cosine_sim

np.float64(0.7462279723150378)

In [26]:
X = np.array([[1,0,3],[0,2,1],[1,1,1],[1,0,2]])

In [27]:
dist_matrix_cosine = cosine_distances(X)

In [28]:
print("dist_matrix_cosine: \n",dist_matrix_cosine)

dist_matrix_cosine: 
 [[0.         0.57573593 0.26970326 0.01005051]
 [0.57573593 0.         0.22540333 0.6       ]
 [0.26970326 0.22540333 0.         0.22540333]
 [0.01005051 0.6        0.22540333 0.        ]]


In [29]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering(
    n_clusters= 2,
    metric='precomputed',
    linkage='average'
)

In [30]:
labels = clustering.fit_predict(dist_matrix_cosine)

In [31]:
labels

array([1, 0, 0, 1])

In [33]:
clustering = AgglomerativeClustering(
    n_clusters= 3,
    metric='precomputed',
    linkage='average'
)
labels = clustering.fit_predict(dist_matrix_cosine)
labels


array([0, 2, 1, 0])