In [9]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler


In [10]:
X = np.array([[85,92], [70,88], [95,95], [60,80]])

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.71428571, 0.8       ],
       [0.28571429, 0.53333333],
       [1.        , 1.        ],
       [0.        , 0.        ]])

In [11]:
from sklearn.preprocessing import StandardScaler

X = np.array([[170,65], [180,80], [160,55], [175,70]])

In [12]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-0.16903085, -0.2773501 ],
       [ 1.18321596,  1.38675049],
       [-1.52127766, -1.38675049],
       [ 0.50709255,  0.2773501 ]])

In [13]:
from sklearn.preprocessing import RobustScaler

#X = np.array([[100,175,200,400,321,420,501,80000,1000]])
X = np.array([
    [100, 200],
    [150, 250],
    [120, 220],
    [10000, 300]  # Outlier in first column!
])

In [14]:
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-0.01401401, -0.73684211],
       [ 0.00600601,  0.31578947],
       [-0.00600601, -0.31578947],
       [ 3.94994995,  1.36842105]])